stages:
  - build
  - deploy

build:
  image: node:9.11.1
  stage: build
  script:
    - npm install
    - npm run docs:build
  artifacts:
    paths:
      - public

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
      - apk --update --no-cache add sshpass openssh git
  script:
#      - git clone https://${GITLAB_DEPLOY_USERNAME}:${GITLAB_DEPLOY_PASSWORD}@gitlab.evoforge.org/skills/skills-deploy.git
      - TIMESTAMP=`date +%s`
      - TMP_DIR="deployDocs_${TIMESTAMP}"
      - DEST_PATH="/home/${CI_USERNAME}/$TMP_DIR"
      - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "rm -rf /home/${CI_USERNAME}/deployDocs_* && mkdir -p ${DEST_PATH}"
#      - cp backend/target/backend-*.jar backend.jar
      - sshpass -p $CI_PASSWORD scp -r public ${CI_USERNAME}@${CI_IP}:${DEST_PATH}
#      - sshpass -p $CI_PASSWORD scp -r backend.jar ${CI_USERNAME}@${CI_IP}:${DEST_PATH}/skills-deploy
  only:
    - master
